# Generated by Django 5.1.1 on 2026-07-12 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0014_paymentmethod_paymenttransaction_paymentverification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymenttransaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("received", "Received"),
                    ("verified", "Verified"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
